version: 1
release:
  # Branch configuration
  branch: main

  # Version bump type
  defaultBump: patch

  # Version file updates - Configures how version numbers are updated in different files
  version:
    files:
      # package.json - Updates the version field with the new version
      # Example: "version": "1.0.0" -> "version": "1.1.0"
      - path: 'package.json'
        pattern: '"version":\\s*"([^"]+)"' # Matches the version field value
        template: '"version": "${version}"' # Replaces with new version from release

  # Changelog configuration
  changelog:
    enabled: true
    template: conventional

  # Pre-release checks
  checks:
    - type: build
      command: 'make build-arm64'

  # Release actions actions
  actions:
    - type: git-tag
    - type: commit-push
    - type: github-release
      assets:
        - 'out/link_arm64'
    - type: custom
      name: 'update-go-mod'
      command: |
        VERSION=$(node -p "require('./package.json').version")
        go mod edit -module "$(go list -m)"/v${VERSION%%.*}
        go mod tidy
